import type { Metadata } from 'next'
import { Paper, ThemeProvider } from '@mui/material'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import { Toaster } from 'react-hot-toast'

import StoreProvider from './StoreProvider'
import localFont from 'next/font/local'
import theme from '@/theme'
import './globals.css'
import AppBarComp from './components/ControlBarComponents/AppBar'

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900'
})
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900'
})

export const metadata: Metadata = {
    title: 'NEXTJS_ExhibitBlog',
    description: 'Generated by create next app Exhibit Blog'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <StoreProvider>
                    <AppRouterCacheProvider options={{ key: 'css' }}>
                        <ThemeProvider theme={theme}>
                            <Paper sx={{ height: '100vh' }}>
                                <AppBarComp />
                                {children}
                                <Toaster position="top-center" reverseOrder={false} />
                            </Paper>
                        </ThemeProvider>
                    </AppRouterCacheProvider>
                </StoreProvider>
            </body>
        </html>
    )
}
